// Code generated by Arduino IoT Cloud, DO NOT EDIT.

/* CUSTOM LINE: Added for VScode error removal*/
#if defined (ARDUINO)

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBLEMOTORSPEEDCLOUDChange();
void onBLEEMERGENCYCLOUDChange();

float BLE_MOTOR_SPEED_CLOUD;
bool BLE_EMERGENCY_CLOUD;

void initProperties() {

  ArduinoCloud.addProperty(BLE_MOTOR_SPEED_CLOUD, READWRITE, ON_CHANGE, onBLEMOTORSPEEDCLOUDChange);
  ArduinoCloud.addProperty(BLE_EMERGENCY_CLOUD, READWRITE, ON_CHANGE, onBLEEMERGENCYCLOUDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

#endif
